app:
  image: jeanberu/akeneo-pim
  container_name: akeneo_pim
  links:
    - mysql:mysql
    - mongo:mongo
  volumes:
    - /home/julien/workspace/pim-community-standard:/var/www/html
  ports:
    - 8080:80
mysql:
  image: mysql:latest
  container_name: akeneo_pim_mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: akeneo_pim
    MYSQL_USER: akeneo_pim
    MYSQL_PASSWORD: akeneo_pim
mongo:
  image: mongo:2.4
  container_name: akeneo_pim_mongo